services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules #Ajout des dépendances par dessus
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - hackathon_network

  frontend:
    image: nginx:1.27.3
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/js:/usr/share/nginx/html/js
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hackathon_network

  db:
    image: mariadb:11.6.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3307:3306"
    volumes:
      #- db_data:/var/lib/mysql  #Garder les données
      - ./backend/BDD/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - hackathon_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  hackathon_network: