services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"  # Le port est exposé pour permettre l'accès depuis l'extérieur du conteneur
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    network_mode: "host"
    

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/js:/usr/share/nginx/html/js
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hackathon_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network: